site_name: CCG - Creating Your Teaching Kit
site_url: https://climatecompatiblegrowth.github.io/course_test/
repo_url: https://github.com/ClimateCompatibleGrowth/course_test
edit_uri: edit/mkdocs/docs/
site_author: Climate Compatible Growth
copyright: Copyright Climate Compatible Growth 2020

markdown_extensions:
  - attr_list

theme:
    name: bootstrap4

nav:
  - Home: index.md

plugins:
  - search
  - git-committers:
      repository: ClimateCompatibleGrowth/course_test
      branch: mkdocs
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
